version: '3.9'

networks:
  net1:

services:
  app:
    container_name: rostislav-comments-app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net1

  db:
    container_name: rostislav-comments-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: rostislav11
      POSTGRES_USER: rostislav
      POSTGRES_DB: hotel-manager
    volumes:
      - db-data:/var/lib/postresql/data
    networks:
      - net1

volumes:
  db-data: