version: '3.9'

networks:
  net1:

services:
  db:
    container_name: rostislav-hotels-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: rostislav11
      POSTGRES_USER: rostislav
      POSTGRES_DB: hotel-manager
    volumes:
      - db-data:/var/lib/postresql/data
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    networks:
      - net1

  maildev:
    container_name: maildev
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - net1

volumes:
  db-data:
