spring.application.name=MyHotel


# Data Source Properties
spring.datasource.driverClassName=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Properties
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
spring.jpa.hibernate.ddl-auto=${JPA_HBM2DDL_AUTO}
###Logging Levels
# Disable the default loggers
logging.level.org = INFO
logging.level.blog = INFO

#Show SQL executed with parameter bindings
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type.descriptor = TRACE

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

spring.boot.admin.client.url=http://localhost:8099/api/v1/admin